title: Aleksandr Penskoi
logo: /assets/img/prof_pic_small.jpeg
description: |
    Associate Professor <br/>
    at <a href="https://scs.ifmo.ru/ru/">SE&CS Faculty</a> <br/>
    at <a href="https://en.itmo.ru">ITMO University</a> <br/>
    Russia 
    <hr/>
    Associate Professor <br/>
    at <a href="http://joint.hdu.edu.cn/en/">HDU-ITMO Joint Institute</a><br/>
    China
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
author: Aleksandr Penskoi

collections:
  projects:
    output: true
    permalink: /projects/:path/
  courses:
    output: true
    permalink: /courses/:path/
